# Generated by Django 2.2.10 on 2021-02-15 12:41

from django.db import migrations, models
import django.db.models.deletion
import polls_test_service_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test_service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4098)),
                ('q_type', models.SmallIntegerField(default=polls_test_service_app.models.QuestionType(0))),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls_test_service_app.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls_test_service_app.Question')),
            ],
        ),
    ]
