# Generated by Django 2.2.10 on 2021-02-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test_service_app', '0002_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('arbitrary', models.CharField(default=None, null=True, max_length=255)),
                ('choice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls_test_service_app.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls_test_service_app.Question')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls_test_service_app.Poll')),
            ],
        ),
    ]
